import mongoose from 'mongoose';

const LocalidadSchema = new mongoose.Schema({
  name: { 
    type: String, 
    required: true, 
    unique: true,
    enum: [
      "Abramo",
      "Adolfo Van Praet",
      "Agustoni",
      "Algarrobo del Águila",
      "Alpachiri",
      "Alta Italia",
      "Anguil",
      "Arata",
      "Ataliva Roca",
      "Bernardo Larroudé",
      "Bernasconi",
      "Caleufú",
      "Carro Quemado",
      "Catriló",
      "Ceballos",
      "Chacharramendi",
      "Colonia Barón",
      "Colonia Santa María",
      "Conhello",
      "Coronel Hilario Lagos",
      "Cuchillo Có",
      "Doblas",
      "Dorila",
      "Eduardo Castex",
      "Embajador Martini",
      "Falucho",
      "General Acha",
      "General Manuel Campos",
      "General Pico",
      "General San Martín",
      "Gobernador Duval",
      "Guatraché",
      "Ingeniero Luiggi",
      "Intendente Alvear",
      "Jacinto Arauz",
      "La Adela",
      "La Humada",
      "La Maruja",
      "La Reforma",
      "Limay Mahuida",
      "Lonquimay",
      "Loventuel",
      "Luan Toro",
      "Macachín",
      "Maisonnave",
      "Mauricio Mayer",
      "Metileo",
      "Miguel Cané",
      "Miguel Riglos",
      "Monte Nievas",
      "Parera",
      "Peru",
      "Pichi Huinca",
      "Puelches",
      "Puelén",
      "Quehué",
      "Quemú Quemú",
      "Quetrequén",
      "Rancul",
      "Realicó",
      "Relmo",
      "Rolón",
      "Rucanelo",
      "Sarah",
      "Santa Isabel",
      "Santa Rosa",
      "Santa Teresa",
      "Speluzzi",
      "Telén",
      "Toay",
      "Tomás Manuel Anchorena",
      "Trenel",
      "Unanue",
      "Uriburu",
      "Vértiz",
      "Victorica",
      "Villa Mirasol",
      "Winifreda"
    ]
  }
});

export default mongoose.model('Localidad', LocalidadSchema, 'localidades'); 